---
#
# SPDX-License-Identifier: GPL-3.0-or-later

# NOTE: most functionality (apart from building) is abstracted by this include
include:
  - project: 'archlinux/ci-scripts'
    ref: master
    file: '/prepare_archiso_vm.yml'

variables:
  BUILD_SCRIPT: ./.gitlab/ci/build_archiso_profiles.sh
  PACKAGE_LIST: base-devel cryptsetup docbook-xsl dosfstools e2fsprogs erofs-utils git jq libisoburn mtools openssl pango qemu-headless shellcheck shfmt squashfs-tools zsync
  QEMU_BUILD_TIMEOUT: 2400
  QEMU_COPY_ARTIFACTS_TIMEOUT: 120
  QEMU_VM_MEMORY: 3072
  ARCHISO_COW_SPACE_SIZE: 2g

stages:
  - build

build_short:
  extends: .build
  parallel:
    matrix:
      - BUILD_SCRIPT_ARGS: ebaseline bootstrap
      - BUILD_SCRIPT_ARGS: desktop bootstrap
      - BUILD_SCRIPT_ARGS: ereleng bootstrap

build_long:
  extends: .build
  parallel:
    matrix:
      - BUILD_SCRIPT_ARGS: ebaseline iso
      - BUILD_SCRIPT_ARGS: desktop iso 
      - BUILD_SCRIPT_ARGS: ereleng iso
      - BUILD_SCRIPT_ARGS: ebaseline keys
      - BUILD_SCRIPT_ARGS: desktop keys
      - BUILD_SCRIPT_ARGS: ereleng keys
  tags:
    - fast-single-thread
